-- =====================================================
-- CALLBACK FLYWAY: afterMigrate.sql
-- Verificações e otimizações pós-migração
-- Gerado em: 2025-09-24
-- =====================================================

-- =====================================================
-- SEÇÃO 0: ATUALIZAÇÃO DE VIGÊNCIA RETROATIVA
-- Objetivo: Atualizar datas de início de vigência de 2026-01-01 para 2025-01-01
-- em todas as tabelas que possuem colunas com sufixo '_inicio_vigencia'.

-- Descomente e execute o script abaixo sempre que houver atualização de estrutura (criaçao de tabela nova) e atualize os updates para que todas as tabelas estejam cobertas.
-- Essas atualizações devem ser removidas antes de entrar em producao. 
-- =====================================================
-- SELECT
--     'UPDATE ' || m.name || ' SET ' || p.name || ' = ''2025-01-01'' WHERE ' || p.name || ' = ''2026-01-01'';'
-- FROM sqlite_master m
-- JOIN pragma_table_info(m.name) p
-- WHERE m.type = 'table'
--   AND p.name LIKE '%inicio_vigencia'
--   ORDER BY m.name ASC;
-- =====================================================

UPDATE AJUSTE SET AJST_INICIO_VIGENCIA = '2025-01-01' WHERE AJST_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_REM SET AARE_INICIO_VIGENCIA = '2025-01-01' WHERE AARE_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_REM_PRODUTO SET AARP_INICIO_VIGENCIA = '2025-01-01' WHERE AARP_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_REM_SERVICO SET AARS_INICIO_VIGENCIA = '2025-01-01' WHERE AARS_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_VALOREM SET AADV_INICIO_VIGENCIA = '2025-01-01' WHERE AADV_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_VALOREM_PRODUTO SET AAVP_INICIO_VIGENCIA = '2025-01-01' WHERE AAVP_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_AD_VALOREM_SERVICO SET AAVS_INICIO_VIGENCIA = '2025-01-01' WHERE AAVS_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_PADRAO SET ALPA_INICIO_VIGENCIA = '2025-01-01' WHERE ALPA_INICIO_VIGENCIA = '2026-01-01';
UPDATE ALIQUOTA_REFERENCIA SET ALRE_INICIO_VIGENCIA = '2025-01-01' WHERE ALRE_INICIO_VIGENCIA = '2026-01-01';
UPDATE ANEXO SET ANXO_INICIO_VIGENCIA = '2025-01-01' WHERE ANXO_INICIO_VIGENCIA = '2026-01-01';
UPDATE APROPRIACAO_CREDITO_ADQUIRENTE SET APCA_INICIO_VIGENCIA = '2025-01-01' WHERE APCA_INICIO_VIGENCIA = '2026-01-01';
UPDATE CLASSIFICACAO_TRIBUTARIA SET CLTR_INICIO_VIGENCIA = '2025-01-01' WHERE CLTR_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_AD_REM_PRODUTO SET EARP_INICIO_VIGENCIA = '2025-01-01' WHERE EARP_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_AD_REM_SERVICO SET EARS_INICIO_VIGENCIA = '2025-01-01' WHERE EARS_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_AD_VALOREM_PRODUTO SET EAVP_INICIO_VIGENCIA = '2025-01-01' WHERE EAVP_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_AD_VALOREM_SERVICO SET EAVS_INICIO_VIGENCIA = '2025-01-01' WHERE EAVS_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_NBS_APLICAVEL SET ENBS_INICIO_VIGENCIA = '2025-01-01' WHERE ENBS_INICIO_VIGENCIA = '2026-01-01';
UPDATE EXCECAO_NCM_APLICAVEL SET ENCM_INICIO_VIGENCIA = '2025-01-01' WHERE ENCM_INICIO_VIGENCIA = '2026-01-01';
UPDATE FUNDAMENTACAO_CLASSIFICACAO SET FDCL_INICIO_VIGENCIA = '2025-01-01' WHERE FDCL_INICIO_VIGENCIA = '2026-01-01';
UPDATE FUNDAMENTACAO_LEGAL SET FDLG_INICIO_VIGENCIA = '2025-01-01' WHERE FDLG_INICIO_VIGENCIA = '2026-01-01';
UPDATE NBS SET NBS_INICIO_VIGENCIA = '2025-01-01' WHERE NBS_INICIO_VIGENCIA = '2026-01-01';
UPDATE NBS_APLICAVEL SET NBSA_INICIO_VIGENCIA = '2025-01-01' WHERE NBSA_INICIO_VIGENCIA = '2026-01-01';
UPDATE NCM SET NCM_INICIO_VIGENCIA = '2025-01-01' WHERE NCM_INICIO_VIGENCIA = '2026-01-01';
UPDATE NCM_APLICAVEL SET NCMA_INICIO_VIGENCIA = '2025-01-01' WHERE NCMA_INICIO_VIGENCIA = '2026-01-01';
UPDATE PERCENTUAL_REDUCAO SET PERE_INICIO_VIGENCIA = '2025-01-01' WHERE PERE_INICIO_VIGENCIA = '2026-01-01';
UPDATE REDUTOR SET RDTO_INICIO_VIGENCIA = '2025-01-01' WHERE RDTO_INICIO_VIGENCIA = '2026-01-01';
UPDATE SITUACAO_TRIBUTARIA SET SITR_INICIO_VIGENCIA = '2025-01-01' WHERE SITR_INICIO_VIGENCIA = '2026-01-01';
UPDATE TIPO_DFE SET TPDF_INICIO_VIGENCIA = '2025-01-01' WHERE TPDF_INICIO_VIGENCIA = '2026-01-01';
UPDATE TIPO_DFE_CLASSIFICACAO SET TDCL_INICIO_VIGENCIA = '2025-01-01' WHERE TDCL_INICIO_VIGENCIA = '2026-01-01';
UPDATE TOMADOR_ESPECIFICO SET TMES_INICIO_VIGENCIA = '2025-01-01' WHERE TMES_INICIO_VIGENCIA = '2026-01-01';
UPDATE TRATAMENTO_CLASSIFICACAO SET TRCL_INICIO_VIGENCIA = '2025-01-01' WHERE TRCL_INICIO_VIGENCIA = '2026-01-01';
UPDATE TRATAMENTO_TRIBUTARIO SET TRTR_INICIO_VIGENCIA = '2025-01-01' WHERE TRTR_INICIO_VIGENCIA = '2026-01-01';
UPDATE TRIBUTO SET TBTO_INICIO_VIGENCIA = '2025-01-01' WHERE TBTO_INICIO_VIGENCIA = '2026-01-01';
UPDATE TRIBUTO_SITUACAO_TRIBUTARIA SET TRST_INICIO_VIGENCIA = '2025-01-01' WHERE TRST_INICIO_VIGENCIA = '2026-01-01';
UPDATE UNIDADE_MEDIDA SET UNMD_INICIO_VIGENCIA = '2025-01-01' WHERE UNMD_INICIO_VIGENCIA = '2026-01-01';

-- =====================================================
-- SEÇÃO 1: VERIFICAÇÕES DE INTEGRIDADE
-- =====================================================

-- Verifica integridade geral do banco
PRAGMA integrity_check;

-- Verifica consistência de chaves estrangeiras
PRAGMA foreign_key_check;

-- Verifica se foreign keys estão habilitadas
SELECT 
    CASE 
        WHEN foreign_keys = 1 THEN '✅ Foreign keys HABILITADAS'
        ELSE '❌ Foreign keys DESABILITADAS - PROBLEMA!'
    END as status_fk
FROM PRAGMA_foreign_keys();

-- =====================================================
-- SEÇÃO 2: ANÁLISE DE PERFORMANCE
-- =====================================================

-- Atualiza estatísticas para otimização de consultas
ANALYZE;

-- Executa otimizações automáticas
PRAGMA optimize;

-- Verifica tamanho das tabelas principais
SELECT 
    name as tabela,
    ROUND((
        SELECT COUNT(*) * 
        (SELECT AVG(length(sql)) FROM sqlite_master WHERE type='table' AND name=m.name)
        FROM sqlite_master WHERE type='table' AND name=m.name
    ) / 1024.0, 2) || ' KB' as tamanho_estimado
FROM sqlite_master m
WHERE type = 'table' 
AND name NOT LIKE 'sqlite_%'
AND name NOT LIKE 'flyway_%'
ORDER BY name;

-- =====================================================
-- FIM DAS VERIFICAÇÕES
-- =====================================================

-- Mensagem final
SELECT '🎉 Verificações pós-migração concluídas com sucesso!' as status_final;

-- =====================================================
-- CALLBACK afterMigrate.sql - CONCLUÍDO
-- =====================================================
